cbb_teams = ['North Carolina', 'Wisconsin', 'Michigan', 'Texas Tech', 'Gonzaga',
       'Kentucky', 'Duke', 'Virginia', 'Villanova', 'Connecticut',
       'Louisville', 'Notre Dame', 'Florida St.', 'Purdue', 'Kansas',
       'Kansas St.', 'Xavier', 'Arizona', 'Oregon', 'Florida',
       'Michigan St.', 'Dayton', 'Ohio St.', 'Marquette', 'Syracuse',
       'Oklahoma', 'Loyola Chicago', 'South Carolina', 'Auburn',
       'Wichita St.', 'Duquesne', 'Fordham', 'George Mason',
       'George Washington', 'La Salle', 'Massachusetts', 'Rhode Island',
       'Richmond', "Saint Joseph's", 'Saint Louis', 'St. Bonaventure',
       'Davidson', 'VCU', 'Boston College', 'Clemson', 'Georgia Tech',
       'Miami FL', 'Pittsburgh', 'Virginia Tech', 'Wake Forest',
       'North Carolina St.', 'Binghamton', 'Hartford', 'Maine',
       'New Hampshire', 'Stony Brook', 'UMass Lowell', 'UMBC', 'Vermont',
       'Albany', 'East Carolina', 'Houston', 'Memphis', 'South Florida',
       'Temple', 'Tulane', 'Tulsa', 'UCF', 'SMU', 'Florida Gulf Coast',
       'Jacksonville', 'Kennesaw St.', 'Lipscomb', 'Northern Kentucky',
       'Stetson', 'USC Upstate', 'NJIT', 'North Florida', 'North Alabama',
       'Illinois', 'Minnesota', 'Nebraska', 'Northwestern', 'Penn St.',
       'Rutgers', 'Indiana', 'Iowa', 'Maryland', 'TCU', 'Oklahoma St.',
       'Texas', 'Baylor', 'Iowa St.', 'West Virginia', 'Creighton',
       'DePaul', 'Seton Hall', 'Georgetown', "St. John's", 'Butler',
       'Providence', 'Idaho', 'Idaho St.', 'Montana', 'Montana St.',
       'North Dakota', 'Northern Arizona', 'Northern Colorado',
       'Portland St.', 'Sacramento St.', 'Southern Utah', 'Weber St.',
       'Eastern Washington', 'Campbell', 'Charleston Southern',
       'Gardner Webb', 'High Point', 'Liberty', 'Longwood',
       'Presbyterian', 'Radford', 'UNC Asheville', 'Winthrop',
       'Coastal Carolina', 'Hampton', 'Cal Poly', 'Cal St. Fullerton',
       'Cal St. Northridge', 'Hawaii', 'Long Beach St.', 'UC Davis',
       'UC Riverside', 'UC Santa Barbara', 'UC Irvine',
       'College of Charleston', 'Delaware', 'Drexel', 'Elon', 'Hofstra',
       'James Madison', 'Towson', 'UNC Wilmington', 'William & Mary',
       'Northeastern', 'Charlotte', 'FIU', 'Florida Atlantic',
       'Louisiana Tech', 'Marshall', 'Middle Tennessee', 'North Texas',
       'Old Dominion', 'Rice', 'Southern Miss', 'UTEP', 'UTSA',
       'Western Kentucky', 'UAB', 'Cleveland St.', 'Detroit', 'Green Bay',
       'Illinois Chicago', 'Milwaukee', 'Oakland', 'Wright St.',
       'Youngstown St.', 'Valparaiso', 'IUPUI', 'Brown', 'Columbia',
       'Cornell', 'Dartmouth', 'Penn', 'Princeton', 'Yale', 'Harvard',
       'Canisius', 'Fairfield', 'Iona', 'Marist', 'Monmouth', 'Niagara',
       'Quinnipiac', 'Rider', "Saint Peter's", 'Siena', 'Manhattan',
       'Akron', 'Ball St.', 'Bowling Green', 'Central Michigan',
       'Eastern Michigan', 'Kent St.', 'Miami OH', 'Northern Illinois',
       'Ohio', 'Toledo', 'Western Michigan', 'Buffalo', 'Bethune Cookman',
       'Coppin St.', 'Delaware St.', 'Florida A&M', 'Howard',
       'Maryland Eastern Shore', 'Morgan St.', 'Norfolk St.',
       'North Carolina A&T', 'North Carolina Central', 'Savannah St.',
       'South Carolina St.', 'Bradley', 'Drake', 'Evansville',
       'Illinois St.', 'Indiana St.', 'Missouri St.', 'Southern Illinois',
       'Northern Iowa', 'Air Force', 'Colorado St.', 'Fresno St.',
       'Nevada', 'New Mexico', 'San Jose St.', 'UNLV', 'Utah St.',
       'Boise St.', 'San Diego St.', 'Wyoming', 'Bryant',
       'Central Connecticut', 'Fairleigh Dickinson', 'LIU Brooklyn',
       "Mount St. Mary's", 'Sacred Heart', 'St. Francis NY',
       'St. Francis PA', 'Wagner', 'Robert Morris', 'Austin Peay',
       'Eastern Illinois', 'Eastern Kentucky', 'Jacksonville St.',
       'Morehead St.', 'Murray St.', 'SIU Edwardsville',
       'Southeast Missouri St.', 'Tennessee Martin', 'Tennessee St.',
       'Tennessee Tech', 'Belmont', 'Arizona St.', 'California',
       'Colorado', 'Oregon St.', 'Stanford', 'USC', 'Washington',
       'Washington St.', 'UCLA', 'Utah', 'American', 'Army',
       'Boston University', 'Bucknell', 'Colgate', 'Holy Cross', 'Lehigh',
       'Loyola MD', 'Navy', 'Lafayette', 'Appalachian St.',
       'Arkansas Little Rock', 'Arkansas St.', 'Georgia Southern',
       'Louisiana Lafayette', 'Louisiana Monroe', 'South Alabama',
       'Texas St.', 'Troy', 'UT Arlington', 'Georgia St.', 'Little Rock',
       'Chattanooga', 'East Tennessee St.', 'Furman', 'Mercer', 'Samford',
       'The Citadel', 'UNC Greensboro', 'VMI', 'Western Carolina',
       'Wofford', 'Alabama', 'Mississippi St.', 'Missouri', 'Tennessee',
       'Texas A&M', 'Vanderbilt', 'Arkansas', 'Georgia', 'LSU',
       'Mississippi', 'Abilene Christian', 'Central Arkansas',
       'Houston Baptist', 'Incarnate Word', 'Lamar', 'McNeese St.',
       'New Orleans', 'Nicholls St.', 'Northwestern St.',
       'Sam Houston St.', 'Southeastern Louisiana',
       'Texas A&M Corpus Chris', 'Stephen F. Austin', 'Denver', 'IPFW',
       'Nebraska Omaha', 'Oral Roberts', 'South Dakota',
       'South Dakota St.', 'Western Illinois', 'North Dakota St.',
       'Fort Wayne', 'Alabama A&M', 'Alabama St.', 'Alcorn St.',
       'Arkansas Pine Bluff', 'Grambling St.', 'Jackson St.',
       'Mississippi Valley St.', 'Prairie View A&M', 'Southern',
       'Texas Southern', 'Cal St. Bakersfield', 'Chicago St.',
       'Grand Canyon', 'Seattle', 'UMKC', 'UT Rio Grande Valley',
       'Utah Valley', 'New Mexico St.', 'Cal Baptist', 'Loyola Marymount',
       'Pacific', 'Pepperdine', 'Portland', "Saint Mary's", 'San Diego',
       'San Francisco', 'Santa Clara', 'BYU', 'Cincinnati']
